import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-app.js';
import {getAuth,signInAnonymously} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import {getDatabase,ref,set,get,update,onValue,onDisconnect} from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-database.js';
import {firebaseConfig,isFirebaseConfigured} from '../firebase-config.js';
import {GAME_TYPE,LOCATIONS,randomRoomCode,pickLocation,assignRound,escapeHtml} from './game-core.js';

const $=id=>document.getElementById(id);let db,auth,uid='',room='',players={},pub={},mine={},truth={},timerId=null,hostVote='';
const path=(p='')=>`rooms/${room}${p?'/'+p:''}`;const entries=()=>Object.entries(players).sort((a,b)=>(a[1].joinedAt||0)-(b[1].joinedAt||0));
function renderPlayers(){const list=entries();$('playerCount').textContent=`${list.length} คน`;$('playerList').innerHTML=list.length?list.map(([id,p])=>`<div class="player"><span><span class="dot ${p.connected===false?'off':''}"></span>${escapeHtml(p.name)}${id===uid?' • คุณ':''}</span><span class="muted">${p.assigned?'พร้อม':'รอ'}</span></div>`).join(''):'<div class="muted">ยังไม่มีผู้เล่น</div>';$('startBtn').disabled=list.length<3||pub.state==='playing'||pub.state==='accusation'}
function secretHtml(d){if(!d?.roundId)return'';if(d.isSpy)return`<div class="secret-title">บทบาทลับ</div><div class="secret-main">🕵️ SPY</div><div class="secret-sub">คุณไม่รู้สถานที่ • ฟังคำตอบและพยายามเดาให้ได้</div>`;return`<div class="secret-title">สถานที่</div><div class="secret-main">${escapeHtml(d.location)}</div><div class="secret-sub">บทบาทของคุณ: <b>${escapeHtml(d.role)}</b></div>`}
function renderSecret(){const ok=Boolean(mine?.roundId);$('hostSecret').classList.toggle('hidden',!ok);if(ok){$('secretCard').innerHTML=secretHtml(mine);$('secretCard').classList.toggle('spy',Boolean(mine.isSpy));ensureSpyGuess()}}
function fmt(ms){const s=Math.max(0,Math.ceil(ms/1000));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startTimer(){clearInterval(timerId);const tick=async()=>{if(pub.state!=='playing'||!pub.endsAt)return;const left=pub.endsAt-Date.now();$('timer').textContent=fmt(left);$('timer').classList.toggle('low',left<=60000);if(left<=0){clearInterval(timerId);await finishRound('spy','หมดเวลา — Spy ชนะ')}};tick();timerId=setInterval(tick,250)}
function renderPhase(){const playing=pub.state==='playing',acc=pub.state==='accusation',result=pub.state==='result';$('timerBox').classList.toggle('hidden',!playing);$('accuseBox').classList.add('hidden');$('voteBox').classList.toggle('hidden',!acc);$('resultBox').classList.toggle('hidden',!result);if(playing)startTimer();else clearInterval(timerId);if(acc){const suspect=players?.[pub.suspectUid]?.name||'ผู้เล่น';$('voteProgress').textContent=`กำลังโหวต: ${suspect}`;renderHostVote()}if(result)$('resultText').textContent=pub.resultText||'จบรอบ'}
function render(){const created=Boolean(room);$('createView').classList.toggle('hidden',created);$('roomView').classList.toggle('hidden',!created);if(created)$('roomCode').textContent=room;renderPlayers();renderSecret();renderPhase()}
function attach(){onValue(ref(db,path('players')),s=>{players=s.val()||{};render()});onValue(ref(db,path('public')),s=>{pub=s.val()||{};render()});onValue(ref(db,path(`private/${uid}`)),s=>{mine=s.val()||{};render()});onValue(ref(db,path('hostSecret')),s=>{truth=s.val()||{}});onValue(ref(db,path('spyGuess')),async s=>{const g=s.val();if(g&&pub.state==='playing'&&truth?.location){await finishRound(g.location===truth.location?'spy':'citizens',g.location===truth.location?`Spy เดาถูก: ${truth.location} — Spy ชนะ`:`Spy เดาผิด (${g.location}) • สถานที่คือ ${truth.location} — ฝ่ายผู้เล่นชนะ`)}})}
async function createRoom(){const name=$('hostName').value.trim();if(!name)return alert('กรุณาใส่ชื่อ');let code='';for(let i=0;i<10;i++){const c=randomRoomCode();if(!(await get(ref(db,`rooms/${c}/hostUid`))).exists()){code=c;break}}if(!code)return alert('สร้างห้องไม่สำเร็จ');room=code;localStorage.setItem('spyfall_host_room',room);localStorage.setItem('spyfall_host_name',name);await set(ref(db,path('hostUid')),uid);await set(ref(db,path('public')),{gameType:GAME_TYPE,state:'lobby',roundNumber:0,duration:Number($('duration').value),createdAt:Date.now()});await update(ref(db,path(`players/${uid}`)),{name,isHost:true,connected:true,joinedAt:Date.now(),assigned:false});try{await onDisconnect(ref(db,path(`players/${uid}/connected`))).set(false)}catch{}attach();render()}
async function startRound(){const list=entries();if(list.length<3)return alert('ต้องมีผู้เล่นอย่างน้อย 3 คน');const location=pickLocation(),{spyUid,assignments}=assignRound(list,location),roundNumber=Number(pub.roundNumber||0)+1,roundId=`r_${Date.now().toString(36)}`,duration=Number(pub.duration||$('duration').value||480),endsAt=Date.now()+duration*1000,u={};for(const[id]of list){u[`private/${id}`]={...assignments[id],roundId,roundNumber};u[`players/${id}/assigned`]=true}u.hostSecret={roundId,spyUid,location:location.name};u.spyGuess=null;u.spyVotes=null;u.public={gameType:GAME_TYPE,state:'playing',roundId,roundNumber,duration,endsAt,startedAt:Date.now()};await update(ref(db,path()),u);$('secretCard').classList.add('hidden');$('revealBtn').textContent='🔒 แตะเพื่อดูการ์ดของฉัน'}
function fillSuspects(){const opts=entries().map(([id,p])=>`<option value="${id}">${escapeHtml(p.name)}</option>`).join('');$('suspectSelect').innerHTML=opts}
async function openAccusation(){fillSuspects();$('accuseBox').classList.remove('hidden')}
async function beginVote(){const suspectUid=$('suspectSelect').value;if(!suspectUid)return;const accusationId=`a_${Date.now().toString(36)}`;hostVote='';await update(ref(db,path()),{spyVotes:null,'public/state':'accusation','public/accusationId':accusationId,'public/suspectUid':suspectUid,'public/accusedAt':Date.now()})}
function renderHostVote(){if(pub.suspectUid===uid)return;let box=$('hostVoteBox');if(!box){box=document.createElement('div');box.id='hostVoteBox';box.className='stack';box.innerHTML='<div class="vote-options"><button id="hostYes" class="btn danger">ใช่ เป็น Spy</button><button id="hostNo" class="btn safe">ไม่ใช่</button></div><button id="hostVoteSubmit" class="btn primary" disabled>ล็อกคะแนนของฉัน</button>';$('voteBox').insertBefore(box,$('closeVoteBtn'));$('hostYes').onclick=()=>{hostVote='yes';$('hostVoteSubmit').disabled=false};$('hostNo').onclick=()=>{hostVote='no';$('hostVoteSubmit').disabled=false};$('hostVoteSubmit').onclick=async()=>{if(hostVote)await set(ref(db,path(`spyVotes/${pub.accusationId}/${uid}`)),{choice:hostVote,submittedAt:Date.now()})}}}
async function closeVote(){const snap=await get(ref(db,path(`spyVotes/${pub.accusationId}`))),votes=snap.val()||{},eligible=entries().filter(([id])=>id!==pub.suspectUid).map(([id])=>id),missing=eligible.filter(id=>!votes[id]);if(missing.length&&!confirm(`ยังขาด ${missing.length} คะแนน ปิดโหวตหรือไม่?`))return;const yes=eligible.filter(id=>votes[id]?.choice==='yes').length,no=eligible.filter(id=>votes[id]?.choice==='no').length;if(yes===eligible.length&&eligible.length>0){if(pub.suspectUid===truth.spyUid)await finishRound('citizens',`จับ Spy สำเร็จ • ${players[pub.suspectUid]?.name||'Spy'} คือ Spy • สถานที่: ${truth.location}`);else await finishRound('spy',`กล่าวหาผิดคน • Spy ชนะ • Spy คือ ${players[truth.spyUid]?.name||'ผู้เล่น'} • สถานที่: ${truth.location}`)}else{await update(ref(db,path()),{'public/state':'playing','public/accusationId':null,'public/suspectUid':null,'public/voteSummary':{yes,no},spyVotes:null});alert(`ข้อกล่าวหาไม่ผ่าน • ใช่ ${yes} / ไม่ใช่ ${no}`)}}
async function finishRound(winner,text){if(pub.state==='result')return;await update(ref(db,path()),{'public/state':'result','public/winner':winner,'public/resultText':text,'public/endedAt':Date.now()})}
function ensureSpyGuess(){if(!mine?.isSpy||pub.state!=='playing')return;let box=$('hostSpyGuess');if(box)return;box=document.createElement('div');box.id='hostSpyGuess';box.className='panel stack';box.style.marginTop='14px';box.innerHTML='<h3>คุณเป็น Spy — เดาสถานที่</h3><select id="hostLocationGuess"></select><button id="hostGuessBtn" class="btn danger">ยืนยันคำตอบ</button>';document.querySelector('.wrap').appendChild(box);$('hostLocationGuess').innerHTML=LOCATIONS.map(x=>`<option>${escapeHtml(x.name)}</option>`).join('');$('hostGuessBtn').onclick=async()=>{if(confirm('ยืนยันการเดาสถานที่?'))await set(ref(db,path('spyGuess')),{uid,location:$('hostLocationGuess').value,roundId:pub.roundId,submittedAt:Date.now()})}}
async function copyLink(){const u=new URL('./player.html',location.href);u.searchParams.set('room',room);try{await navigator.clipboard.writeText(u.toString());$('copyBtn').textContent='คัดลอกแล้ว ✓';setTimeout(()=>$('copyBtn').textContent='คัดลอกลิงก์ผู้เล่น',1200)}catch{prompt('คัดลอกลิงก์',u.toString())}}
$('createBtn').onclick=createRoom;$('startBtn').onclick=startRound;$('copyBtn').onclick=copyLink;$('revealBtn').onclick=()=>{const c=$('secretCard'),hide=!c.classList.contains('hidden');c.classList.toggle('hidden',hide);$('revealBtn').textContent=hide?'🔒 แตะเพื่อดูการ์ดของฉัน':'🙈 ซ่อนการ์ด'};$('accuseBtn').onclick=openAccusation;$('openVoteBtn').onclick=beginVote;$('closeVoteBtn').onclick=closeVote;$('endBtn').onclick=()=>finishRound('spy',`Host จบรอบ • Spy คือ ${players[truth.spyUid]?.name||'ผู้เล่น'} • สถานที่: ${truth.location}`);$('nextBtn').onclick=startRound;
(async()=>{try{if(!isFirebaseConfigured())throw new Error('Firebase config ไม่ครบ');const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);uid=(await signInAnonymously(auth)).user.uid;$('connection').textContent='Firebase พร้อม';$('hostName').value=localStorage.getItem('spyfall_host_name')||'';const saved=localStorage.getItem('spyfall_host_room');if(saved){const s=await get(ref(db,`rooms/${saved}/hostUid`));if(s.val()===uid){room=saved;attach();render()}}}catch(e){console.error(e);$('connection').textContent='เชื่อม Firebase ไม่สำเร็จ';$('createBtn').disabled=true}})();